/*
 * in user api
 * in user api
 *
 * OpenAPI spec version: 2.5.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fr.ans.in.user.api;

import fr.ans.in.user.model.ContactInfos;
import fr.ans.in.user.model.User;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserApi
 */
@Ignore
public class UserApiTest {

    private final UserApi api = new UserApi();

    /**
     * Get User Info by User ID
     *
     * Retrieve the information of the user with the matching user ID.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserByIdTest() {
        String nationalId = null;
        User response = api.getUserById(nationalId);

        // TODO: test validations
    }
    /**
     * Update User Contact Information
     *
     * Update the information of an existing user.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putUsersContactInfosTest() {
        String nationalId = null;
        ContactInfos body = null;
        api.putUsersContactInfos(nationalId, body);

        // TODO: test validations
    }
}
