/*
 * in user api
 * in user api
 *
 * OpenAPI spec version: 2.5.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fr.ans.in.user.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.Serializable;
/**
 * UserUserCivilStatusInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-25T17:18:27.062Z[GMT]")
public class UserUserCivilStatusInfo implements Serializable{
  private static final long serialVersionUID = 1L;
  @JsonProperty("lastName")
  private String lastName = null;

  @JsonProperty("firstnames")
  private String firstnames = null;

  @JsonProperty("birthdate")
  private String birthdate = null;

  @JsonProperty("birthTownCode")
  private String birthTownCode = null;

  @JsonProperty("birthCountryCode")
  private String birthCountryCode = null;

  @JsonProperty("birthplace")
  private String birthplace = null;

  @JsonProperty("genderCode")
  private String genderCode = null;

  @JsonProperty("phone")
  private String phone = null;

  @JsonProperty("email")
  private String email = null;

  public UserUserCivilStatusInfo lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @Schema(required = true, description = "")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public UserUserCivilStatusInfo firstnames(String firstnames) {
    this.firstnames = firstnames;
    return this;
  }

   /**
   * Get firstnames
   * @return firstnames
  **/
  @Schema(required = true, description = "")
  public String getFirstnames() {
    return firstnames;
  }

  public void setFirstnames(String firstnames) {
    this.firstnames = firstnames;
  }

  public UserUserCivilStatusInfo birthdate(String birthdate) {
    this.birthdate = birthdate;
    return this;
  }

   /**
   * Get birthdate
   * @return birthdate
  **/
  @Schema(required = true, description = "")
  public String getBirthdate() {
    return birthdate;
  }

  public void setBirthdate(String birthdate) {
    this.birthdate = birthdate;
  }

  public UserUserCivilStatusInfo birthTownCode(String birthTownCode) {
    this.birthTownCode = birthTownCode;
    return this;
  }

   /**
   * Get birthTownCode
   * @return birthTownCode
  **/
  @Schema(required = true, description = "")
  public String getBirthTownCode() {
    return birthTownCode;
  }

  public void setBirthTownCode(String birthTownCode) {
    this.birthTownCode = birthTownCode;
  }

  public UserUserCivilStatusInfo birthCountryCode(String birthCountryCode) {
    this.birthCountryCode = birthCountryCode;
    return this;
  }

   /**
   * Get birthCountryCode
   * @return birthCountryCode
  **/
  @Schema(required = true, description = "")
  public String getBirthCountryCode() {
    return birthCountryCode;
  }

  public void setBirthCountryCode(String birthCountryCode) {
    this.birthCountryCode = birthCountryCode;
  }

  public UserUserCivilStatusInfo birthplace(String birthplace) {
    this.birthplace = birthplace;
    return this;
  }

   /**
   * Get birthplace
   * @return birthplace
  **/
  @Schema(required = true, description = "")
  public String getBirthplace() {
    return birthplace;
  }

  public void setBirthplace(String birthplace) {
    this.birthplace = birthplace;
  }

  public UserUserCivilStatusInfo genderCode(String genderCode) {
    this.genderCode = genderCode;
    return this;
  }

   /**
   * Get genderCode
   * @return genderCode
  **/
  @Schema(required = true, description = "")
  public String getGenderCode() {
    return genderCode;
  }

  public void setGenderCode(String genderCode) {
    this.genderCode = genderCode;
  }

  public UserUserCivilStatusInfo phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  @Schema(required = true, description = "")
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public UserUserCivilStatusInfo email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @Schema(required = true, description = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserUserCivilStatusInfo userUserCivilStatusInfo = (UserUserCivilStatusInfo) o;
    return Objects.equals(this.lastName, userUserCivilStatusInfo.lastName) &&
        Objects.equals(this.firstnames, userUserCivilStatusInfo.firstnames) &&
        Objects.equals(this.birthdate, userUserCivilStatusInfo.birthdate) &&
        Objects.equals(this.birthTownCode, userUserCivilStatusInfo.birthTownCode) &&
        Objects.equals(this.birthCountryCode, userUserCivilStatusInfo.birthCountryCode) &&
        Objects.equals(this.birthplace, userUserCivilStatusInfo.birthplace) &&
        Objects.equals(this.genderCode, userUserCivilStatusInfo.genderCode) &&
        Objects.equals(this.phone, userUserCivilStatusInfo.phone) &&
        Objects.equals(this.email, userUserCivilStatusInfo.email);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lastName, firstnames, birthdate, birthTownCode, birthCountryCode, birthplace, genderCode, phone, email);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserUserCivilStatusInfo {\n");
    
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    firstnames: ").append(toIndentedString(firstnames)).append("\n");
    sb.append("    birthdate: ").append(toIndentedString(birthdate)).append("\n");
    sb.append("    birthTownCode: ").append(toIndentedString(birthTownCode)).append("\n");
    sb.append("    birthCountryCode: ").append(toIndentedString(birthCountryCode)).append("\n");
    sb.append("    birthplace: ").append(toIndentedString(birthplace)).append("\n");
    sb.append("    genderCode: ").append(toIndentedString(genderCode)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
